'📚 documentation / examples':
  - www/**
  - examples/**
'@trpc/server':
  - packages/server/**
'@trpc/client':
  - packages/client/**
'@trpc/next':
  - packages/next/**
'@trpc/react':
  - packages/react/**
